export enum ValidationErrorType {
  INVALID_FORMAT = 'INVALID_FORMAT',
  INVALID_SENDER_ID = 'INVALID_SENDER_ID',
  INVALID_RECIPIENT_ID = 'INVALID_RECIPIENT_ID',
  INVALID_MESSAGE_TYPE = 'INVALID_MESSAGE_TYPE',
  INVALID_TIMESTAMP = 'INVALID_TIMESTAMP',
  UNKNOWN = 'UNKNOWN',
}
